version: "2"

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "2333:2333"
    environment:
      - SERVER_PORT=2333
      - METHOD=aes-256-gcm
      - PASSWORD=yuyuko
